In [1]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
sent = ["Brown Dog Chasing White rabbit",
       "White Rabbit run into Green gate",
       "Dog jumped over Green ate to catch rabbit",
       "Brown og lost rabbit in green grass"]

In [5]:
sent

['Brown Dog Chasing White rabbit',
 'White Rabbit run into Green gate',
 'Dog jumped over Green ate to catch rabbit',
 'Brown og lost rabbit in green grass']

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cvec = CountVectorizer()

In [8]:
cvec

CountVectorizer()

In [9]:
cvec.fit(sent)

CountVectorizer()

In [13]:
cvec.vocabulary_

{'brown': 1,
 'dog': 4,
 'chasing': 3,
 'white': 17,
 'rabbit': 14,
 'run': 15,
 'into': 9,
 'green': 7,
 'gate': 5,
 'jumped': 10,
 'over': 13,
 'ate': 0,
 'to': 16,
 'catch': 2,
 'og': 12,
 'lost': 11,
 'in': 8,
 'grass': 6}

In [14]:
cvec.get_feature_names_out()

array(['ate', 'brown', 'catch', 'chasing', 'dog', 'gate', 'grass',
       'green', 'in', 'into', 'jumped', 'lost', 'og', 'over', 'rabbit',
       'run', 'to', 'white'], dtype=object)

In [15]:
cvec.transform(sent)

<4x18 sparse matrix of type '<class 'numpy.int64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [16]:
ary = cvec.transform(sent).toarray()

In [17]:
ary

array([[0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0]],
      dtype=int64)

In [18]:
sent

['Brown Dog Chasing White rabbit',
 'White Rabbit run into Green gate',
 'Dog jumped over Green ate to catch rabbit',
 'Brown og lost rabbit in green grass']

In [29]:
cvec.get_feature_names_out()

array(['ate', 'brown', 'catch', 'chasing', 'dog', 'gate', 'grass',
       'green', 'in', 'into', 'jumped', 'lost', 'og', 'over', 'rabbit',
       'run', 'to', 'white'], dtype=object)

In [31]:
pd.DataFrame(ary,columns = cvec.get_feature_names_out())

ate  brown  catch  chasing  dog  gate  grass  green  in  into  jumped  \
0    0      1      0        1    1     0      0      0   0     0       0   
1    0      0      0        0    0     1      0      1   0     1       0   
2    1      0      1        0    1     0      0      1   0     0       1   
3    0      1      0        0    0     0      1      1   1     0       0   

   lost  og  over  rabbit  run  to  white  
0     0   0     0       1    0   0      1  
1     0   0     0       1    1   0      1  
2     0   0     1       1    0   1      0  
3     1   1     0       1    0   0      0

In [33]:
from sklearn.feature_extraction.text import TfidfTransformer

In [35]:
tftrans = TfidfTransformer()

In [37]:
tftrans

TfidfTransformer()

In [39]:
tftrans.fit(ary)

TfidfTransformer()

In [41]:
tftrans.transform(ary)

<4x18 sparse matrix of type '<class 'numpy.float64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [43]:
sent

['Brown Dog Chasing White rabbit',
 'White Rabbit run into Green gate',
 'Dog jumped over Green ate to catch rabbit',
 'Brown og lost rabbit in green grass']

In [45]:
ary

array([[0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0]],
      dtype=int64)

In [47]:
tftrans.transform(ary).toarray()

array([[0.        , 0.44513219, 0.        , 0.56459374, 0.44513219,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.29462843,
        0.        , 0.        , 0.44513219],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.48216873, 0.        , 0.30776206, 0.        , 0.48216873,
        0.        , 0.        , 0.        , 0.        , 0.25161565,
        0.48216873, 0.        , 0.38014737],
       [0.39836776, 0.        , 0.39836776, 0.        , 0.31407771,
        0.        , 0.        , 0.25427298, 0.        , 0.        ,
        0.39836776, 0.        , 0.        , 0.39836776, 0.20788482,
        0.        , 0.39836776, 0.        ],
       [0.        , 0.34242138, 0.        , 0.        , 0.        ,
        0.        , 0.4343181 , 0.27721962, 0.4343181 , 0.        ,
        0.        , 0.4343181 , 0.4343181 , 0.        , 0.2266452 ,
        0.        , 0.        , 0.        ]])

In [49]:
from sklearn.naive_bayes import MultinomialNB

### TFIDF Vectorization

In [52]:
sent

['Brown Dog Chasing White rabbit',
 'White Rabbit run into Green gate',
 'Dog jumped over Green ate to catch rabbit',
 'Brown og lost rabbit in green grass']

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [56]:
tfvec = TfidfVectorizer()

In [58]:
tfvec

TfidfVectorizer()

In [60]:
tfvec.fit(sent)

TfidfVectorizer()

In [66]:
tfvec.get_feature_names_out()

array(['ate', 'brown', 'catch', 'chasing', 'dog', 'gate', 'grass',
       'green', 'in', 'into', 'jumped', 'lost', 'og', 'over', 'rabbit',
       'run', 'to', 'white'], dtype=object)

In [68]:
tfvec.vocabulary_

{'brown': 1,
 'dog': 4,
 'chasing': 3,
 'white': 17,
 'rabbit': 14,
 'run': 15,
 'into': 9,
 'green': 7,
 'gate': 5,
 'jumped': 10,
 'over': 13,
 'ate': 0,
 'to': 16,
 'catch': 2,
 'og': 12,
 'lost': 11,
 'in': 8,
 'grass': 6}

In [62]:
tfvec.transform(sent)

<4x18 sparse matrix of type '<class 'numpy.float64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [64]:
tfvec.transform(sent).toarray()

array([[0.        , 0.44513219, 0.        , 0.56459374, 0.44513219,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.29462843,
        0.        , 0.        , 0.44513219],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.48216873, 0.        , 0.30776206, 0.        , 0.48216873,
        0.        , 0.        , 0.        , 0.        , 0.25161565,
        0.48216873, 0.        , 0.38014737],
       [0.39836776, 0.        , 0.39836776, 0.        , 0.31407771,
        0.        , 0.        , 0.25427298, 0.        , 0.        ,
        0.39836776, 0.        , 0.        , 0.39836776, 0.20788482,
        0.        , 0.39836776, 0.        ],
       [0.        , 0.34242138, 0.        , 0.        , 0.        ,
        0.        , 0.4343181 , 0.27721962, 0.4343181 , 0.        ,
        0.        , 0.4343181 , 0.4343181 , 0.        , 0.2266452 ,
        0.        , 0.        , 0.        ]])